package com.pingbits.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONNECTION.
 */
public class Connection {

    private Long id;
    private String name;
    private String email;
    private Integer dpResource;

    public Connection() {
    }

    public Connection(Long id) {
        this.id = id;
    }

    public Connection(Long id, String name, String email, Integer dpResource) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.dpResource = dpResource;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getDpResource() {
        return dpResource;
    }

    public void setDpResource(Integer dpResource) {
        this.dpResource = dpResource;
    }

}
